"""empty message

Revision ID: 853495c80046
Revises: 7a166a08eaef
Create Date: 2017-02-26 18:31:50.319039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853495c80046'
down_revision = '7a166a08eaef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('password', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user_profile', ['password'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.drop_column('user_profile', 'password')
    # ### end Alembic commands ###
